### ISSUE TITLE
/mnt throwing error on Windows

### ISSUE THREAD

**Issue by TheJaredWilcurt** [saschanaz/flif-wasm#2]
I've created a script to test this. Works fine on Ubuntu/OSX. Throws an error on Windows, likely due to the `/mnt/` prefix in the file path.

**Script:**
* https://github.com/FLIF-hub/node-flif/blob/master/try.js

**Error:**
```
C:\projects\node-flif>node try.js
FLIF (Free Lossless Image Format) 0.3 [28 April 2017]
Error: input file does not exist: /mnt/c/projects/node-flif/sample/cat.flif
child_process.js:634
    throw err;
    ^

Error: Command failed: node "C:\projects\node-flif\node_modules\flif-wasm\lib\flif-wasm.js" -d ./sample/cat.flif ./sample/try.png
Error: input file does not exist: /mnt/c/projects/node-flif/sample/cat.flif

    at checkExecSyncError (child_process.js:591:13)
    at execSync (child_process.js:631:13)
    at runCommandSync (C:\projects\node-flif\try.js:11:17)
    at Object.<anonymous> (C:\projects\node-flif\try.js:25:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
```

**Comment by TheJaredWilcurt** [comment]
**Update:**

I updated to Node 8.9.0 and it works now? I'll keep this open until I can figure out what caused it.

**Comment by TheJaredWilcurt** [comment]
Confirmed that the issue is caused by #1 
Closing this as a duplicate.
